---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - addons.projectcapsule.dev
  resources:
  - accessrequests
  - accessrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.projectcapsule.dev
  resources:
  - accessrequests/finalizers
  - accessrules/finalizers
  verbs:
  - update
- apiGroups:
  - addons.projectcapsule.dev
  resources:
  - accessrequests/status
  - accessrules/status
  verbs:
  - get
  - patch
  - update
