//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/peak-scale/break-the-glass/internal/items"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEntity) DeepCopyInto(out *AccessEntity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEntity.
func (in *AccessEntity) DeepCopy() *AccessEntity {
	if in == nil {
		return nil
	}
	out := new(AccessEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessRequestStatusConditionItem) DeepCopyInto(out *AccessRequestStatusConditionItem) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
	out.Reviewer = in.Reviewer
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessRequestStatusConditionItem.
func (in *AccessRequestStatusConditionItem) DeepCopy() *AccessRequestStatusConditionItem {
	if in == nil {
		return nil
	}
	out := new(AccessRequestStatusConditionItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivePeriod) DeepCopyInto(out *ActivePeriod) {
	*out = *in
	in.ActiveFrom.DeepCopyInto(&out.ActiveFrom)
	in.ActiveUntil.DeepCopyInto(&out.ActiveUntil)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePeriod.
func (in *ActivePeriod) DeepCopy() *ActivePeriod {
	if in == nil {
		return nil
	}
	out := new(ActivePeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovedProperties) DeepCopyInto(out *ApprovedProperties) {
	*out = *in
	out.Duration = in.Duration
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make(items.Items, len(*in))
		for key, val := range *in {
			var outVal *runtime.RawExtension
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(runtime.RawExtension)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovedProperties.
func (in *ApprovedProperties) DeepCopy() *ApprovedProperties {
	if in == nil {
		return nil
	}
	out := new(ApprovedProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequest) DeepCopyInto(out *BreakRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequest.
func (in *BreakRequest) DeepCopy() *BreakRequest {
	if in == nil {
		return nil
	}
	out := new(BreakRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestList) DeepCopyInto(out *BreakRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BreakRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestList.
func (in *BreakRequestList) DeepCopy() *BreakRequestList {
	if in == nil {
		return nil
	}
	out := new(BreakRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestSpec) DeepCopyInto(out *BreakRequestSpec) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(items.TemplateParams, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.Requestor = in.Requestor
	out.Duration = in.Duration
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestSpec.
func (in *BreakRequestSpec) DeepCopy() *BreakRequestSpec {
	if in == nil {
		return nil
	}
	out := new(BreakRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestStatus) DeepCopyInto(out *BreakRequestStatus) {
	*out = *in
	if in.Review != nil {
		in, out := &in.Review, &out.Review
		*out = new(ReviewInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(TemplateProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.Approved != nil {
		in, out := &in.Approved, &out.Approved
		*out = new(ApprovedProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(ActivePeriod)
		(*in).DeepCopyInto(*out)
	}
	in.KeepUntil.DeepCopyInto(&out.KeepUntil)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestStatus.
func (in *BreakRequestStatus) DeepCopy() *BreakRequestStatus {
	if in == nil {
		return nil
	}
	out := new(BreakRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestTemplate) DeepCopyInto(out *BreakRequestTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestTemplate.
func (in *BreakRequestTemplate) DeepCopy() *BreakRequestTemplate {
	if in == nil {
		return nil
	}
	out := new(BreakRequestTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakRequestTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestTemplateList) DeepCopyInto(out *BreakRequestTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BreakRequestTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestTemplateList.
func (in *BreakRequestTemplateList) DeepCopy() *BreakRequestTemplateList {
	if in == nil {
		return nil
	}
	out := new(BreakRequestTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakRequestTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestTemplateSpec) DeepCopyInto(out *BreakRequestTemplateSpec) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make(items.TemplateItems, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.DefaultDuration = in.DefaultDuration
	out.MaxDuration = in.MaxDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestTemplateSpec.
func (in *BreakRequestTemplateSpec) DeepCopy() *BreakRequestTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(BreakRequestTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestTemplateStatus) DeepCopyInto(out *BreakRequestTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestTemplateStatus.
func (in *BreakRequestTemplateStatus) DeepCopy() *BreakRequestTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(BreakRequestTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewInfo) DeepCopyInto(out *ReviewInfo) {
	*out = *in
	if in.Reviewer != nil {
		in, out := &in.Reviewer, &out.Reviewer
		*out = new(AccessEntity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewInfo.
func (in *ReviewInfo) DeepCopy() *ReviewInfo {
	if in == nil {
		return nil
	}
	out := new(ReviewInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateProperties) DeepCopyInto(out *TemplateProperties) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make(items.TemplateItems, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.DefaultDuration = in.DefaultDuration
	out.MaxDuration = in.MaxDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateProperties.
func (in *TemplateProperties) DeepCopy() *TemplateProperties {
	if in == nil {
		return nil
	}
	out := new(TemplateProperties)
	in.DeepCopyInto(out)
	return out
}
