//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/projectcapsule/capsule/api/v1beta2"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEntity) DeepCopyInto(out *AccessEntity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEntity.
func (in *AccessEntity) DeepCopy() *AccessEntity {
	if in == nil {
		return nil
	}
	out := new(AccessEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessRequestStatusConditionItem) DeepCopyInto(out *AccessRequestStatusConditionItem) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
	out.Reviewer = in.Reviewer
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessRequestStatusConditionItem.
func (in *AccessRequestStatusConditionItem) DeepCopy() *AccessRequestStatusConditionItem {
	if in == nil {
		return nil
	}
	out := new(AccessRequestStatusConditionItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequest) DeepCopyInto(out *BreakRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequest.
func (in *BreakRequest) DeepCopy() *BreakRequest {
	if in == nil {
		return nil
	}
	out := new(BreakRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestList) DeepCopyInto(out *BreakRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BreakRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestList.
func (in *BreakRequestList) DeepCopy() *BreakRequestList {
	if in == nil {
		return nil
	}
	out := new(BreakRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestSpec) DeepCopyInto(out *BreakRequestSpec) {
	*out = *in
	out.Requestor = in.Requestor
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Duration = in.Duration
	out.KeepFor = in.KeepFor
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestSpec.
func (in *BreakRequestSpec) DeepCopy() *BreakRequestSpec {
	if in == nil {
		return nil
	}
	out := new(BreakRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestStatus) DeepCopyInto(out *BreakRequestStatus) {
	*out = *in
	if in.Review != nil {
		in, out := &in.Review, &out.Review
		*out = new(BreakRequestStatusReview)
		(*in).DeepCopyInto(*out)
	}
	if in.Approved != nil {
		in, out := &in.Approved, &out.Approved
		*out = new(BreakRequestStatusReviewProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(BreakRequestStatusActive)
		(*in).DeepCopyInto(*out)
	}
	in.KeepUntil.DeepCopyInto(&out.KeepUntil)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestStatus.
func (in *BreakRequestStatus) DeepCopy() *BreakRequestStatus {
	if in == nil {
		return nil
	}
	out := new(BreakRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestStatusActive) DeepCopyInto(out *BreakRequestStatusActive) {
	*out = *in
	in.ActiveFrom.DeepCopyInto(&out.ActiveFrom)
	in.ActiveUntil.DeepCopyInto(&out.ActiveUntil)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestStatusActive.
func (in *BreakRequestStatusActive) DeepCopy() *BreakRequestStatusActive {
	if in == nil {
		return nil
	}
	out := new(BreakRequestStatusActive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestStatusReview) DeepCopyInto(out *BreakRequestStatusReview) {
	*out = *in
	if in.Reviewer != nil {
		in, out := &in.Reviewer, &out.Reviewer
		*out = new(AccessEntity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestStatusReview.
func (in *BreakRequestStatusReview) DeepCopy() *BreakRequestStatusReview {
	if in == nil {
		return nil
	}
	out := new(BreakRequestStatusReview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakRequestStatusReviewProperties) DeepCopyInto(out *BreakRequestStatusReviewProperties) {
	*out = *in
	out.KeepFor = in.KeepFor
	out.Duration = in.Duration
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakRequestStatusReviewProperties.
func (in *BreakRequestStatusReviewProperties) DeepCopy() *BreakRequestStatusReviewProperties {
	if in == nil {
		return nil
	}
	out := new(BreakRequestStatusReviewProperties)
	in.DeepCopyInto(out)
	return out
}
